Object #<Inflate> has no method 'destroy'
Fix for supporting safe errors on corrupted PNG files.

Actually, when a png file is corrupted the following fatal error is
thrown:

TypeError: Object #<Inflate> has no method 'destroy'

instead of emit a regular ’error’.